trigger:
- master

jobs:
- job: FindUnion
  pool:
    vmImage: ubuntu-latest


  steps:
  - template: iterable.yml
    parameters:
      repositories: ["hugo", "paco", "luis"]

  - task: AzureKeyVault@1
    displayName: 'Download secrets'
    inputs:
      azureSubscription: 'ramp-up-kv-service'
      keyVaultName: 'ramp-up-kv'
      secretsFilter: '*'
      runAsPreJob: false

  - script: |
      sudo apt-get update
      sudo apt-get install -y wget cmake g++
    displayName: 'Installation of additional packages'

  - script: sh build.sh
    displayName: 'build project'

  - script: sh test.sh
    displayName: 'test project'
