trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y cmake g++

- script: cmake .
  displayName: 'cmake project configuration'

- script: |
    make clean
    make
  displayName: 'build project'

- script: make test
  displayName: 'test project'
