trigger:
- master

pool:
  vmImage: ubuntu-latest
  demands: cmake g++
  
steps:
- script: cmake .
  displayName: 'cmake project configuration'

- script: |
    make clean
    make
  displayName: 'build project'

- script: make test
  displayName: 'test project'
