trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y wget cmake g++
  displayName: 'Installation of additional packages'

- script: |
    wget -qO- https://github.com/google/googletest/archive/release-1.10.0.tar.gz | tar xvzf -
    cd googletest-release-1.10.0
    cmake .
    make
    cd -
    cmake .
    make clean
    make
  displayName: 'cmake project configuration'

- script: |
    make clean
    make
  displayName: 'build project'

- script: make test
  displayName: 'test project'
