trigger:
- master

jobs:
- job: FindUnion
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'f26db95a-32ff-486c-976e-1a63b1486f21'
      keyVaultName: 'ramp-up-kv'
      secretsFilter: '*'
      runAsPreJob: false

  - script: |
      sudo apt-get update
      sudo apt-get install -y wget cmake g++
    displayName: 'Installation of additional packages'

  - script: sh build.sh
    displayName: 'build project'

  - script: sh test.sh
    displayName: 'test project'
