trigger:
- master

jobs:
- job: FindUnion
  pool:
    vmImage: debian-10

  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y wget cmake g++
    displayName: 'Installation of additional packages'

  - script: sh build.sh
    displayName: 'build project'

  - script: sh test.sh
    displayName: 'test project'
